apps/bank_web/web/router.ex
defmodule BankWeb.Router do
  use BankWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BankWeb.Authentication
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BankWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/sign_in", SessionController, :new
    post "/sign_in", SessionController, :create
    post "/sign_in_as/:username", SessionController, :sign_in_as
    get "/sign_out", SessionController, :sign_out

    get "/account", AccountController, :show

    get "/transfers/new", TransferController, :new
    post "/transfers", TransferController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", BankWeb do
  #   pipe_through :api
  # end
end

apps/bank_web/web/controllers/account_controller.ex
defmodule BankWeb.AccountController do
  use BankWeb.Web, :controller
  plug :require_authenticated

  def show(conn, _params) do
    customer = conn.assigns.current_customer
    balance = Bank.balance(customer)
    transactions = Bank.transactions(customer)

    render conn, "show.html", balance: balance, transactions: transactions
  end
end

apps/bank_web/web/controllers/page_controller.ex
defmodule BankWeb.PageController do
  use BankWeb.Web, :controller
  plug :require_authenticated

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/bank_web/web/controllers/session_controller.ex
defmodule BankWeb.SessionController do
  use BankWeb.Web, :controller

  def new(conn, _params) do
    customers = Bank.customers()
    render conn, "new.html", customers: customers
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Auth.sign_in(email, password) do
      {:ok, account} ->
        customer = Bank.find_customer!(auth_account_id: account.id)

        conn
        |> put_session(:customer_id, customer.id)
        |> redirect(to: "/")
      {:error, _} ->
        customers = Bank.customers()
        render(conn, "new.html", customers: customers)
    end
  end

  def sign_in_as(conn, %{"username" => username}) do
		customer = Bank.find_customer!(username: username)

    conn
    |> put_session(:customer_id, customer.id)
    |> redirect(to: "/")
  end

  def sign_out(conn, _params) do
    conn
    |> clear_session()
    |> redirect(to: "/")
  end
end

apps/bank_web/web/controllers/transfer_controller.ex
defmodule BankWeb.TransferController do
  use BankWeb.Web, :controller
  plug :require_authenticated

  def new(conn, _params) do
    customer = conn.assigns.current_customer
    transfer = Bank.build_transfer(customer)
    render conn, "new.html", transfer: transfer
  end

  def create(conn, %{"transfer" => transfer_params}) do
    customer = conn.assigns.current_customer

    case Bank.create_transfer(customer, transfer_params) do
      {:ok, _transfer} ->
        redirect conn, to: account_path(conn, :show)
      {:error, changeset} ->
        changeset = %{changeset | action: :transfer}
        render conn, "new.html", transfer: changeset
    end
  end
end

apps/bank_web/web/views/account_view.ex
defmodule BankWeb.AccountView do
  use BankWeb.Web, :view

  def format_amount(%Bank.Ledger.Entry{type: type, amount: amount}) do
    sign(type) <> format_money(amount)
  end

  defp sign("credit"), do: "+"
  defp sign("debit"), do: "-"

  def format_money(%Money{} = money) do
    [value, currency] = to_string(money) |> String.split(" ", trim: true)
    do_format_money(value, currency)
  end

  defp do_format_money(value, "USD"), do: "$" <> value
end

apps/bank_web/web/views/error_view.ex
defmodule BankWeb.ErrorView do
  use BankWeb.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/bank_web/web/views/layout_view.ex
defmodule BankWeb.LayoutView do
  use BankWeb.Web, :view

  def nav_link(conn, title, opts) do
    active? = conn.request_path == Keyword.fetch!(opts, :to)
    class = if active?, do: "active", else: ""

    content_tag(:li, link(title, opts), class: class)
  end
end

apps/bank_web/web/views/page_view.ex
defmodule BankWeb.PageView do
  use BankWeb.Web, :view
end

apps/bank_web/web/views/session_view.ex
defmodule BankWeb.SessionView do
  use BankWeb.Web, :view
end

apps/bank_web/web/views/transfer_view.ex
defmodule BankWeb.TransferView do
  use BankWeb.Web, :view
end

apps/bank_web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello BankWeb!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link "BankWeb", to: page_path(@conn, :index), class: "navbar-brand" %>
        </div>

        <%= if @current_customer do %>

          <ul class="nav navbar-nav">
            <%= nav_link @conn, "Account", to: account_path(@conn, :show) %>
          </ul>

          <ul class="nav navbar-nav pull-right">
            <li><%= link "Signed in as #{@current_customer.username}", to: account_path(@conn, :show) %></li>
            <li><%= link "Sign out", to: session_path(@conn, :sign_out) %></li>
          </ul>

        <% end %>
      </div>
    </nav>

    <div class="container">
      <% if flash = get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= flash %></p>
      <% end %>

      <% if flash = get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= flash %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/bank_web/web/templates/page/index.html.eex
<h2>Welcome</h2>

apps/bank_web/web/templates/session/new.html.eex
<h2>Sign in</h2>

<div class="row">
  <div class="col-md-6">
    <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
      <div class="form-group">
        <%= label f, :email %><br/>
        <%= text_input f, :email, class: "form-control" %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-group">
        <%= label f, :password %><br/>
        <%= password_input f, :password, class: "form-control" %>
        <%= error_tag f, :password %>
      </div>

      <div class="form-group">
        <%= submit "Sign in", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<h2>[Debug] Sign in</h2>

<%= for customer <- @customers do %>
  <%= link "Sign in as #{customer.username}", to: session_path(@conn, :sign_in_as, customer.username), method: :post, class: "btn btn-default" %>
<% end %>

apps/bank_web/web/templates/transfer/new.html.eex
<h2>New transfer</h2>

<div class="row">
  <div class="col-md-6">

    <%= form_for @transfer, transfer_path(@conn, :create), fn f -> %>
      <div class="form-group">
        <%= label f, :amount_string, "Amount" %><br/>
        <%= text_input f, :amount_string, class: "form-control" %>
        <%= error_tag f, :amount_string %>
      </div>

      <div class="form-group">
        <%= label f, :destination_username, "Destination username" %><br/>
        <%= text_input f, :destination_username, class: "form-control" %>
        <%= error_tag f, :destination_username %>
      </div>

      <div class="form-group">
        <%= label f, :description %><br/>
        <%= textarea f, :description, class: "form-control" %>
        <%= error_tag f, :description %>
      </div>

      <div class="form-group">
        <%= submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>